// <auto-generated />
using System;
using Catore.Backend.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Catore.Backend.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260922085831_AddGoalModeAndWipeReason")]
    partial class AddGoalModeAndWipeReason
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Catore.Backend.Modules.Auth.Internal.MUser", b =>
                {
                    b.Property<long>("UserPk")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("userPk");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("UserPk"));

                    b.Property<long?>("CreatedBy")
                        .HasColumnType("bigint")
                        .HasColumnName("createdBy");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("createdOn");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<string>("EmailVerifiedToken")
                        .HasColumnType("text")
                        .HasColumnName("emailVerifiedToken");

                    b.Property<DateTime?>("EmailVerifiedTokenExpiredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("emailVerifiedTokenExpiredAt");

                    b.Property<bool>("IsEmailVerif")
                        .HasColumnType("boolean")
                        .HasColumnName("isEmailVerif");

                    b.Property<string>("JwtRefreshToken")
                        .HasColumnType("text")
                        .HasColumnName("jwtRefreshToken");

                    b.Property<DateTime?>("JwtRefreshTokenExpiredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("jwtRefreshTokenExpiredAt");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("text")
                        .HasColumnName("modifiedBy");

                    b.Property<DateTime>("ModifiedOn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modifiedOn");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("password");

                    b.Property<string>("ResetToken")
                        .HasColumnType("text")
                        .HasColumnName("resetToken");

                    b.Property<DateTime?>("ResetTokenExpiredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("resetTokenExpiredAt");

                    b.Property<Guid?>("SessionId")
                        .HasColumnType("uuid")
                        .HasColumnName("sessionId");

                    b.HasKey("UserPk");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("muser", (string)null);
                });

            modelBuilder.Entity("Catore.Backend.Modules.Consumption.Internal.MConsumption", b =>
                {
                    b.Property<long>("ConsumptionPk")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("consumptionPk");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("ConsumptionPk"));

                    b.Property<int>("Calories")
                        .HasColumnType("integer")
                        .HasColumnName("calories");

                    b.Property<long>("CreatedBy")
                        .HasColumnType("bigint")
                        .HasColumnName("createdBy");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("createdOn");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("ConsumptionPk");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("Name", "Calories");

                    b.ToTable("mconsumption", (string)null);
                });

            modelBuilder.Entity("Catore.Backend.Modules.Consumption.Internal.TConsumption", b =>
                {
                    b.Property<long>("EntryPk")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("entryPk");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("EntryPk"));

                    b.Property<long>("ConsumptionId")
                        .HasColumnType("bigint")
                        .HasColumnName("consumptionId");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("createdOn");

                    b.Property<DateTime>("EntryTimestamp")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("entryTimestamp");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("isDeleted");

                    b.Property<DateTime?>("IsDeletedOn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("isDeletedOn");

                    b.Property<long?>("MealType")
                        .HasColumnType("bigint")
                        .HasColumnName("mealType");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("userId");

                    b.HasKey("EntryPk");

                    b.HasIndex("ConsumptionId");

                    b.HasIndex("MealType");

                    b.HasIndex("UserId", "EntryTimestamp");

                    b.ToTable("tconsumption", (string)null);
                });

            modelBuilder.Entity("Catore.Backend.Modules.Consumption.Internal.TDailyRecord", b =>
                {
                    b.Property<long>("DailyRecordPk")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("dailyRecordPk");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("DailyRecordPk"));

                    b.Property<int>("ActualCalories")
                        .HasColumnType("integer")
                        .HasColumnName("actualCalories");

                    b.Property<long?>("CalorieCategory")
                        .HasColumnType("bigint")
                        .HasColumnName("calorieCategory");

                    b.Property<long?>("CreatedVia")
                        .HasColumnType("bigint")
                        .HasColumnName("createdVia");

                    b.Property<decimal>("EffectiveLimit")
                        .HasColumnType("numeric")
                        .HasColumnName("effectiveLimit");

                    b.Property<decimal>("EffectiveTdee")
                        .HasColumnType("numeric")
                        .HasColumnName("effectiveTdee");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("isDeleted");

                    b.Property<DateTime?>("IsDeletedOn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("isDeletedOn");

                    b.Property<bool>("IsFrozen")
                        .HasColumnType("boolean")
                        .HasColumnName("isFrozen");

                    b.Property<DateTime>("ModifiedOn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modifiedOn");

                    b.Property<bool>("PaToday")
                        .HasColumnType("boolean")
                        .HasColumnName("paToday");

                    b.Property<DateOnly>("RecordDate")
                        .HasColumnType("date")
                        .HasColumnName("recordDate");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("userId");

                    b.Property<string>("WipeReason")
                        .HasColumnType("text")
                        .HasColumnName("wipeReason");

                    b.HasKey("DailyRecordPk");

                    b.HasIndex("CalorieCategory");

                    b.HasIndex("CreatedVia");

                    b.HasIndex("UserId", "RecordDate")
                        .IsUnique();

                    b.ToTable("tdailyrecord", (string)null);
                });

            modelBuilder.Entity("Catore.Backend.Modules.Freeze.Internal.TFreeze", b =>
                {
                    b.Property<long>("FreezePk")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("freezePk");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("FreezePk"));

                    b.Property<int>("DaysSinceLastStreakFreeze")
                        .HasColumnType("integer")
                        .HasColumnName("daysSinceLastStreakFreeze");

                    b.Property<int>("DaysSinceLastWipeFreeze")
                        .HasColumnType("integer")
                        .HasColumnName("daysSinceLastWipeFreeze");

                    b.Property<DateOnly?>("LastStreakFreezeGainedDate")
                        .HasColumnType("date")
                        .HasColumnName("lastStreakFreezeGainedDate");

                    b.Property<DateOnly?>("LastWipeFreezeGainedDate")
                        .HasColumnType("date")
                        .HasColumnName("lastWipeFreezeGainedDate");

                    b.Property<DateTime>("ModifiedOn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modifiedOn");

                    b.Property<int>("StreakFreezeCount")
                        .HasColumnType("integer")
                        .HasColumnName("streakFreezeCount");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("userId");

                    b.Property<int>("WipeFreezeCount")
                        .HasColumnType("integer")
                        .HasColumnName("wipeFreezeCount");

                    b.Property<string>("WipeReason")
                        .HasColumnType("text")
                        .HasColumnName("wipeReason");

                    b.HasKey("FreezePk");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("tfreeze", (string)null);
                });

            modelBuilder.Entity("Catore.Backend.Modules.Notification.Internal.TNotification", b =>
                {
                    b.Property<long>("NotificationPk")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("notificationPk");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("NotificationPk"));

                    b.Property<string>("FcmToken")
                        .HasColumnType("text")
                        .HasColumnName("fcmToken");

                    b.Property<DateTime>("ModifiedOn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modifiedOn");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("userId");

                    b.HasKey("NotificationPk");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("tnotification", (string)null);
                });

            modelBuilder.Entity("Catore.Backend.Modules.Param.Internal.MParam", b =>
                {
                    b.Property<long>("ParamPk")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("paramPK");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("ParamPk"));

                    b.Property<long?>("CreatedBy")
                        .HasColumnType("bigint")
                        .HasColumnName("createdBy");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("createdOn");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("ParamType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("paramType");

                    b.Property<int>("Value")
                        .HasColumnType("integer")
                        .HasColumnName("value");

                    b.HasKey("ParamPk");

                    b.HasIndex("ParamType");

                    b.ToTable("mparam", (string)null);
                });

            modelBuilder.Entity("Catore.Backend.Modules.Param.Internal.MParamNotif", b =>
                {
                    b.Property<long>("NotifPk")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("notifPk");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("NotifPk"));

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("body");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("createdOn");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("isActive");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("key");

                    b.Property<DateTime>("ModifiedOn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modifiedOn");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.Property<long?>("Type")
                        .HasColumnType("bigint")
                        .HasColumnName("type");

                    b.HasKey("NotifPk");

                    b.HasIndex("Key")
                        .IsUnique();

                    b.HasIndex("Type");

                    b.ToTable("mparamnotif", (string)null);
                });

            modelBuilder.Entity("Catore.Backend.Modules.ProfileAccount.Internal.MProfile", b =>
                {
                    b.Property<long>("ProfilePk")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("profilePK");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("ProfilePk"));

                    b.Property<int>("Age")
                        .HasColumnType("integer")
                        .HasColumnName("age");

                    b.Property<long?>("BaseActLevel")
                        .HasColumnType("bigint")
                        .HasColumnName("baseActLevel");

                    b.Property<long?>("CreatedBy")
                        .HasColumnType("bigint")
                        .HasColumnName("createdBy");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("createdOn");

                    b.Property<long?>("Gender")
                        .HasColumnType("bigint")
                        .HasColumnName("gender");

                    b.Property<long?>("GoalMode")
                        .HasColumnType("bigint")
                        .HasColumnName("goalMode");

                    b.Property<decimal?>("GoalWeight")
                        .HasColumnType("numeric")
                        .HasColumnName("goalWeight");

                    b.Property<decimal>("Height")
                        .HasColumnType("numeric")
                        .HasColumnName("height");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("isActive");

                    b.Property<bool>("IsRecomendGoalUsed")
                        .HasColumnType("boolean")
                        .HasColumnName("isRecomendGoalUsed");

                    b.Property<bool>("IsUpgraded")
                        .HasColumnType("boolean")
                        .HasColumnName("isUpgraded");

                    b.Property<DateTime?>("LastWipeOn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("lastWipeOn");

                    b.Property<long?>("MetricParam")
                        .HasColumnType("bigint")
                        .HasColumnName("metricParam");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("text")
                        .HasColumnName("modifiedBy");

                    b.Property<DateTime>("ModifiedOn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modifiedOn");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Timezone")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("timezone");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("userId");

                    b.Property<decimal>("Weight")
                        .HasColumnType("numeric")
                        .HasColumnName("weight");

                    b.HasKey("ProfilePk");

                    b.HasIndex("BaseActLevel");

                    b.HasIndex("Gender");

                    b.HasIndex("GoalMode");

                    b.HasIndex("MetricParam");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("mprofile", (string)null);
                });

            modelBuilder.Entity("Catore.Backend.Modules.Streak.Internal.TStreak", b =>
                {
                    b.Property<long>("StreakPk")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("streakPk");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("StreakPk"));

                    b.Property<int>("CurrentStreak")
                        .HasColumnType("integer")
                        .HasColumnName("currentStreak");

                    b.Property<bool>("IsStreakFrozen")
                        .HasColumnType("boolean")
                        .HasColumnName("isStreakFrozen");

                    b.Property<DateOnly?>("LastLoggedDate")
                        .HasColumnType("date")
                        .HasColumnName("lastLoggedDate");

                    b.Property<DateTime>("ModifiedOn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modifiedOn");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("userId");

                    b.Property<string>("WipeReason")
                        .HasColumnType("text")
                        .HasColumnName("wipeReason");

                    b.HasKey("StreakPk");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("tstreak", (string)null);
                });

            modelBuilder.Entity("Catore.Backend.Modules.WeightTracking.Internal.TWeightLog", b =>
                {
                    b.Property<long>("WeightLogPk")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("weightLogPk");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("WeightLogPk"));

                    b.Property<DateOnly>("CheckpointDate")
                        .HasColumnType("date")
                        .HasColumnName("checkpointDate");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("createdOn");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("isDeleted");

                    b.Property<DateTime?>("IsDeletedOn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("isDeletedOn");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modifiedOn");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("userId");

                    b.Property<decimal>("Weight")
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("weight");

                    b.Property<string>("WipeReason")
                        .HasColumnType("text")
                        .HasColumnName("wipeReason");

                    b.HasKey("WeightLogPk");

                    b.HasIndex("UserId", "CheckpointDate")
                        .IsUnique();

                    b.ToTable("tweightlog", (string)null);
                });

            modelBuilder.Entity("Catore.Backend.Modules.Consumption.Internal.MConsumption", b =>
                {
                    b.HasOne("Catore.Backend.Modules.Auth.Internal.MUser", null)
                        .WithMany()
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_mconsumption_createdBy");
                });

            modelBuilder.Entity("Catore.Backend.Modules.Consumption.Internal.TConsumption", b =>
                {
                    b.HasOne("Catore.Backend.Modules.Consumption.Internal.MConsumption", null)
                        .WithMany()
                        .HasForeignKey("ConsumptionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_tconsumption_mconsumption");

                    b.HasOne("Catore.Backend.Modules.Param.Internal.MParam", null)
                        .WithMany()
                        .HasForeignKey("MealType")
                        .HasConstraintName("FK_tconsumption_mealType");

                    b.HasOne("Catore.Backend.Modules.Auth.Internal.MUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_tconsumption_muser");
                });

            modelBuilder.Entity("Catore.Backend.Modules.Consumption.Internal.TDailyRecord", b =>
                {
                    b.HasOne("Catore.Backend.Modules.Param.Internal.MParam", null)
                        .WithMany()
                        .HasForeignKey("CalorieCategory")
                        .HasConstraintName("FK_tdailyrecord_calorieCategory");

                    b.HasOne("Catore.Backend.Modules.Param.Internal.MParam", null)
                        .WithMany()
                        .HasForeignKey("CreatedVia")
                        .HasConstraintName("FK_tdailyrecord_createdVia");

                    b.HasOne("Catore.Backend.Modules.Auth.Internal.MUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_tdailyrecord_muser");
                });

            modelBuilder.Entity("Catore.Backend.Modules.Freeze.Internal.TFreeze", b =>
                {
                    b.HasOne("Catore.Backend.Modules.Auth.Internal.MUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_tfreeze_muser");
                });

            modelBuilder.Entity("Catore.Backend.Modules.Param.Internal.MParamNotif", b =>
                {
                    b.HasOne("Catore.Backend.Modules.Param.Internal.MParam", null)
                        .WithMany()
                        .HasForeignKey("Type")
                        .HasConstraintName("FK_mparamnotif_type");
                });

            modelBuilder.Entity("Catore.Backend.Modules.ProfileAccount.Internal.MProfile", b =>
                {
                    b.HasOne("Catore.Backend.Modules.Param.Internal.MParam", null)
                        .WithMany()
                        .HasForeignKey("BaseActLevel")
                        .HasConstraintName("FK_mprofile_baseActLevel");

                    b.HasOne("Catore.Backend.Modules.Param.Internal.MParam", null)
                        .WithMany()
                        .HasForeignKey("Gender")
                        .HasConstraintName("FK_mprofile_gender");

                    b.HasOne("Catore.Backend.Modules.Param.Internal.MParam", null)
                        .WithMany()
                        .HasForeignKey("GoalMode")
                        .HasConstraintName("FK_mprofile_goalMode");

                    b.HasOne("Catore.Backend.Modules.Param.Internal.MParam", null)
                        .WithMany()
                        .HasForeignKey("MetricParam")
                        .HasConstraintName("FK_mprofile_metricParam");

                    b.HasOne("Catore.Backend.Modules.Auth.Internal.MUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_mprofile_muser");
                });

            modelBuilder.Entity("Catore.Backend.Modules.Streak.Internal.TStreak", b =>
                {
                    b.HasOne("Catore.Backend.Modules.Auth.Internal.MUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_tstreak_muser");
                });

            modelBuilder.Entity("Catore.Backend.Modules.WeightTracking.Internal.TWeightLog", b =>
                {
                    b.HasOne("Catore.Backend.Modules.Auth.Internal.MUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_tweightlog_muser");
                });
#pragma warning restore 612, 618
        }
    }
}
