// <auto-generated />
using System;
using Catore.Backend.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Catore.Backend.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260723102554_AddFreezeGainedDates")]
    partial class AddFreezeGainedDates
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Catore.Backend.Modules.Auth.Internal.UserAccount", b =>
                {
                    b.Property<Guid>("UserAccountPk")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("useraccountpk");

                    b.Property<Guid?>("ActiveSessionId")
                        .HasColumnType("uuid")
                        .HasColumnName("activesessionid");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("createdon");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<bool>("IsEmailVerified")
                        .HasColumnType("boolean")
                        .HasColumnName("isemailverified");

                    b.Property<DateTime>("ModifiedOn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modifiedon");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("passwordhash");

                    b.Property<string>("RefreshToken")
                        .HasColumnType("text")
                        .HasColumnName("refreshtoken");

                    b.Property<DateTime?>("RefreshTokenExpiry")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("refreshtokenexpiry");

                    b.Property<string>("ResetToken")
                        .HasColumnType("text")
                        .HasColumnName("resettoken");

                    b.Property<DateTime?>("ResetTokenExpiry")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("resettokenexpiry");

                    b.Property<string>("VerifyToken")
                        .HasColumnType("text")
                        .HasColumnName("verifytoken");

                    b.Property<DateTime?>("VerifyTokenExpiry")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("verifytokenexpiry");

                    b.HasKey("UserAccountPk");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("useraccount", (string)null);
                });

            modelBuilder.Entity("Catore.Backend.Modules.Consumption.Internal.ConsumptionEntry", b =>
                {
                    b.Property<Guid>("ConsumptionEntryPk")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("consumptionentrypk");

                    b.Property<int>("Calories")
                        .HasColumnType("integer")
                        .HasColumnName("calories");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("createdon");

                    b.Property<DateOnly>("EntryDate")
                        .HasColumnType("date")
                        .HasColumnName("entrydate");

                    b.Property<DateTime>("EntryTimestamp")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("entrytimestamp");

                    b.Property<string>("FoodName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("foodname");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("isdeleted");

                    b.Property<DateTime?>("IsDeletedOn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("isdeletedon");

                    b.Property<string>("MealType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("mealtype");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("userid");

                    b.HasKey("ConsumptionEntryPk");

                    b.ToTable("consumptionentry", (string)null);
                });

            modelBuilder.Entity("Catore.Backend.Modules.Consumption.Internal.DailyRecord", b =>
                {
                    b.Property<Guid>("DailyRecordPk")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("dailyrecordpk");

                    b.Property<string>("CreatedVia")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("createdvia");

                    b.Property<string>("DeficitCategory")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("deficitcategory");

                    b.Property<decimal>("EffectiveLimit")
                        .HasColumnType("numeric")
                        .HasColumnName("effectivelimit");

                    b.Property<decimal>("EffectiveTdee")
                        .HasColumnType("numeric")
                        .HasColumnName("effectivetdee");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("isdeleted");

                    b.Property<DateTime?>("IsDeletedOn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("isdeletedon");

                    b.Property<bool>("IsFrozen")
                        .HasColumnType("boolean")
                        .HasColumnName("isfrozen");

                    b.Property<DateTime>("ModifiedOn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modifiedon");

                    b.Property<bool>("PaToday")
                        .HasColumnType("boolean")
                        .HasColumnName("patoday");

                    b.Property<DateOnly>("RecordDate")
                        .HasColumnType("date")
                        .HasColumnName("recorddate");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("userid");

                    b.HasKey("DailyRecordPk");

                    b.HasIndex("UserId", "RecordDate")
                        .IsUnique();

                    b.ToTable("dailyrecord", (string)null);
                });

            modelBuilder.Entity("Catore.Backend.Modules.Freeze.Internal.FreezeState", b =>
                {
                    b.Property<Guid>("FreezeStatePk")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("freezestatepk");

                    b.Property<int>("DaysSinceLastStreakFreeze")
                        .HasColumnType("integer")
                        .HasColumnName("dayssincelaststreakfreeze");

                    b.Property<int>("DaysSinceLastWipeFreeze")
                        .HasColumnType("integer")
                        .HasColumnName("dayssincelastwipefreeze");

                    b.Property<DateOnly?>("LastStreakFreezeGainedDate")
                        .HasColumnType("date")
                        .HasColumnName("laststreakfreezegaineddate");

                    b.Property<DateOnly?>("LastWipeFreezeGainedDate")
                        .HasColumnType("date")
                        .HasColumnName("lastwipefreezegaineddate");

                    b.Property<DateTime>("ModifiedOn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modifiedon");

                    b.Property<int>("StreakFreezeCount")
                        .HasColumnType("integer")
                        .HasColumnName("streakfreezecount");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("userid");

                    b.Property<int>("WipeFreezeCount")
                        .HasColumnType("integer")
                        .HasColumnName("wipefreezecount");

                    b.HasKey("FreezeStatePk");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("freezestate", (string)null);
                });

            modelBuilder.Entity("Catore.Backend.Modules.Notification.Internal.NotificationSubscription", b =>
                {
                    b.Property<Guid>("NotificationSubscriptionPk")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("notificationsubscriptionpk");

                    b.Property<string>("FcmToken")
                        .HasColumnType("text")
                        .HasColumnName("fcmtoken");

                    b.Property<DateTime>("ModifiedOn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modifiedon");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("userid");

                    b.HasKey("NotificationSubscriptionPk");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("notificationsubscription", (string)null);
                });

            modelBuilder.Entity("Catore.Backend.Modules.ProfileAccount.Internal.ProfileAccount", b =>
                {
                    b.Property<Guid>("ProfileAccountPk")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("profileaccountpk");

                    b.Property<int>("Age")
                        .HasColumnType("integer")
                        .HasColumnName("age");

                    b.Property<string>("BaselineActivityLevel")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("baselineactivitylevel");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("displayname");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("gender");

                    b.Property<decimal?>("GoalWeight")
                        .HasColumnType("numeric")
                        .HasColumnName("goalweight");

                    b.Property<bool>("GoalWeightIsManual")
                        .HasColumnType("boolean")
                        .HasColumnName("goalweightismanual");

                    b.Property<decimal>("Height")
                        .HasColumnType("numeric")
                        .HasColumnName("height");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("isdeleted");

                    b.Property<bool>("IsUpgraded")
                        .HasColumnType("boolean")
                        .HasColumnName("isupgraded");

                    b.Property<string>("MetricPreference")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("metricpreference");

                    b.Property<DateTime>("ModifiedOn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modifiedon");

                    b.Property<string>("Timezone")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("timezone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("userid");

                    b.Property<decimal>("WeightCurrent")
                        .HasColumnType("numeric")
                        .HasColumnName("weightcurrent");

                    b.HasKey("ProfileAccountPk");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("profileaccount", (string)null);
                });

            modelBuilder.Entity("Catore.Backend.Modules.Streak.Internal.StreakState", b =>
                {
                    b.Property<Guid>("StreakStatePk")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("streakstatepk");

                    b.Property<int>("CurrentStreakCount")
                        .HasColumnType("integer")
                        .HasColumnName("currentstreakcount");

                    b.Property<DateOnly?>("LastLoggedDate")
                        .HasColumnType("date")
                        .HasColumnName("lastloggeddate");

                    b.Property<DateTime>("ModifiedOn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modifiedon");

                    b.Property<bool>("StreakIsFrozen")
                        .HasColumnType("boolean")
                        .HasColumnName("streakisfrozen");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("userid");

                    b.HasKey("StreakStatePk");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("streakstate", (string)null);
                });

            modelBuilder.Entity("Catore.Backend.Modules.WeightTracking.Internal.WeightLog", b =>
                {
                    b.Property<Guid>("WeightLogPk")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("weightlogpk");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("createdon");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("isdeleted");

                    b.Property<DateTime?>("IsDeletedOn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("isdeletedon");

                    b.Property<DateTime>("LoggedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("loggedat");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modifiedon");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("userid");

                    b.Property<decimal>("WeightValue")
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("weightvalue");

                    b.HasKey("WeightLogPk");

                    b.ToTable("weightlog", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
